branch-defaults:
  master:
    environment: policecomplaints-dev
    group_suffix: null
environment-defaults:
  policecomplaints-dev:
    branch: null
    repository: null
global:
  application_name: policecomplaints
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
